# Generated by Django 3.0.5 on 2020-05-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogok', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
