# Generated by Django 3.0.5 on 2020-05-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogok', '0006_auto_20200527_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image_pics'),
        ),
    ]
