# Generated by Django 3.0.5 on 2020-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogok', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to='image_pics'),
        ),
    ]
