# Generated by Django 3.0.5 on 2020-05-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogok', '0010_auto_20200528_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='images',
        ),
    ]
